### ISSUE TITLE
FYI: another fork

### ISSUE THREAD

**Issue by sixtyfive** [tfree87/pyRenamer#13]
https://gitlab.com/patlefort/pyrenamer

for that one there's also an AUR entry:

https://aur.archlinux.org/packages/python2-pyrenamer

... or perhaps you already knew. Just thought I'd mention.

**Comment by tfree87** [comment]
Thanks for letting me know about this @sixtyfive. I was unaware of other forks out there. I created this fork a while back when it seemed that the software was being unmaintained and I was looking to update the software and switch to Python 3.
