### ISSUE TITLE
[FEATURE] conda environment file

### ISSUE THREAD

**Issue by fperdigon** [tfree87/pyRenamer#16]
It would be nice to run the software without the need to install new libraries on your system python installation.
Also, a solution for a distribution agnostic environment is needed since packages tend to be called differently on different Linux distributions. Also, the libs versions are not the same on each distribution.
To archive that conda package manager with conda virtual environment does the trick.

**Comment by fperdigon** [comment]
I will create a conda environment that works with the current software and push the config file. Also, I will add how to use it on the readme. 
BTW thanks for rescuing this tool

**Comment by tfree87** [comment]
Yes, this sounds like a great idea. I will admit that I am ignorant of Conda as I have never used it, but I am always in favor of making it easier to manage dependencies on any system.

**Comment by TheTimeTombs** [comment]
Closed by #17
